[build]
  publish = "storybook-static"
  command = "npm run build-storybook"

[build.environment]
  NODE_VERSION = "18"

# Redirect rules for Storybook (optional, but helpful for SPA routing)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}
  headers = {X-Robots-Tag = "noindex"}

# Headers for better performance
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
